name: Test Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  test_build_commit:
    runs-on: ubintu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/actions-yarn@v2.0.0
      - run: yarn install
      - run: yarn build
