name: Publish CI Pipeline

on:
  release:
    types:
      - created

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g yarn
      - name: cache package dependecies
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: yarn install, build, and test
        run: |
          yarn
          yarn test
          yarn build
      - name: publish package to npm
        run: npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION }}
