name: Test CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g yarn
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install, build, and test
        run: |
          yarn
          yarn build
          yarn test
      - name: Cypress tests
        run: cd examples/react
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        run: |
          yarn
          yarn cypress-ci:run
